# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'task.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(964, 804)
        MainWindow.setStyleSheet("background-image: url(\"image.webp\");")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.browseButton = QtWidgets.QPushButton(self.centralwidget)
        self.browseButton.setGeometry(QtCore.QRect(50, 60, 151, 51))
        self.browseButton.setStyleSheet("background-color:rgb(0, 0, 0);\n"
"font:   14pt \"MS Shell Dlg 2\";")
        self.browseButton.setObjectName("browseButton")
        # Connect signals to the methods.
        self.combobox = QComboBox(self.centralwidget)
        self.combobox.addItems(['Line', 'Angle', 'Polygon', 'Ellipse'])

        self.combobox.setStyleSheet(
"font:   14pt \"MS Shell Dlg 2\";")
        #self.combobox.
        self.combobox.setGeometry(QtCore.QRect(230, 60, 151, 51))

        self.numberOfPoints = QtWidgets.QLabel(self.centralwidget)
        self.numberOfPoints.setGeometry(QtCore.QRect(410, 60, 160, 51))
        self.numberOfPoints.setText("points Number:")
        self.numberOfPoints.setStyleSheet(
"font:   14pt \"MS Shell Dlg 2\";")
        # creating spin box
        self.spin = QSpinBox(self.centralwidget)
  
        # setting geometry to spin box
        self.spin.setGeometry(580, 60, 151, 51)
        self.spin.setStyleSheet(
"font:   14pt \"MS Shell Dlg 2\";")


        self.results = QtWidgets.QLabel(self.centralwidget)
        self.results.setGeometry(QtCore.QRect(760, 60, 180, 51))
        self.results.setText("area = 667")
        self.results.setStyleSheet(
"font:   14pt \"MS Shell Dlg 2\";")

        self.axial = QtWidgets.QLabel(self.centralwidget)
        self.axial.setGeometry(QtCore.QRect(550, 140, 371, 261))
        self.axial.setText("")
        self.axial.setObjectName("axial")
        self.threeD = QtWidgets.QLabel(self.centralwidget)
        self.threeD.setGeometry(QtCore.QRect(30, 140, 371, 261))
        self.threeD.setText("")
        self.threeD.setObjectName("threeD")
        self.sa = QtWidgets.QLabel(self.centralwidget)
        self.sa.setGeometry(QtCore.QRect(30, 430, 371, 261))
        self.sa.setText("")
        self.sa.setObjectName("sa")
        self.sagital = QtWidgets.QLabel(self.centralwidget)
        self.sagital.setGeometry(QtCore.QRect(550, 430, 371, 261))
        self.sagital.setText("")
        self.sagital.setObjectName("sagital")
        self.dial = QtWidgets.QDial(self.centralwidget)
        self.dial.setGeometry(QtCore.QRect(450, 400, 50, 64))
        self.dial.setMaximum(180)
        self.dial.setProperty("value", 45)
        self.dial.setObjectName("dial")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 964, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.browseButton.setText(_translate("MainWindow", "Browse"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
